[mypy]
python_version = 3.11
mypy_path = backend
explicit_package_bases = True
warn_unused_configs = True

[mypy-yaml]
ignore_missing_imports = True

[mypy-asyncpg]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-redis]
ignore_missing_imports = True
